import * as THREE from './vendor/three.module.min.js';
import {OrbitControls} from './vendor/OrbitControls.js';
export class LabelViewer{
 constructor(container){this.container=container;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#e6ecef');this.camera=new THREE.PerspectiveCamera(34,1,.1,3000);this.camera.up.set(0,0,1);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;container.append(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','Drehbare 3D-Ansicht des Labels');this.renderer.domElement.tabIndex=0;this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=false;this.controls.minDistance=3;this.controls.maxDistance=1200;this.controls.addEventListener('change',()=>this.render());this.scene.add(new THREE.HemisphereLight(0xffffff,0x738393,2.7));const light=new THREE.DirectionalLight(0xffffff,3.2);light.position.set(-30,-45,70);this.scene.add(light);const fill=new THREE.DirectionalLight(0xffffff,1.5);fill.position.set(40,30,25);this.scene.add(fill);this.group=new THREE.Group();this.scene.add(this.group);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.renderer.domElement.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();const offset=this.camera.position.clone().sub(this.controls.target);if(e.key==='+'||e.key==='-')offset.multiplyScalar(e.key==='+'?.85:1.18);else{const axis=e.key==='ArrowLeft'||e.key==='ArrowRight'?new THREE.Vector3(0,0,1):new THREE.Vector3(1,0,0);offset.applyAxisAngle(axis,(e.key==='ArrowLeft'||e.key==='ArrowUp'?1:-1)*.15);}this.camera.position.copy(this.controls.target).add(offset);this.controls.update();this.render();}});}
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.render();}
 setMeshes(parts){for(const obj of [...this.group.children]){obj.geometry.dispose();obj.material.dispose();this.group.remove(obj);}for(const part of parts){const {vertices,triangles}=part.mesh,geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices.flat(),3));geometry.setIndex(triangles.flat());geometry.computeVertexNormals();const material=new THREE.MeshStandardMaterial({color:part.color,roughness:.68,metalness:0,flatShading:true});const mesh=new THREE.Mesh(geometry,material);this.group.add(mesh);}this.box=new THREE.Box3().setFromObject(this.group);const center=this.box.getCenter(new THREE.Vector3()),size=this.box.getSize(new THREE.Vector3());const signature=[size.x,size.y,size.z].map(n=>n.toFixed(2)).join();if(signature!==this.lastSize){this.lastSize=signature;this.reset();}else{this.controls.target.copy(center);this.render();}}
 reset(top=false){if(!this.box)return;this.resize();const size=this.box.getSize(new THREE.Vector3()),center=this.box.getCenter(new THREE.Vector3());const span=Math.max(size.x/Math.max(.45,this.camera.aspect),size.y*1.6,10);const d=span/(2*Math.tan(THREE.MathUtils.degToRad(17)))*1.25;this.controls.target.copy(center);this.camera.position.copy(center).add(top?new THREE.Vector3(0,-.001,d):new THREE.Vector3(d*.12,-d*.64,d*.88));this.camera.lookAt(center);this.camera.near=.1;this.camera.far=Math.max(3000,d*5);this.camera.updateProjectionMatrix();this.controls.update();this.render();}
 zoom(factor){this.camera.position.sub(this.controls.target).multiplyScalar(factor).add(this.controls.target);this.controls.update();this.render();}
 render(){this.renderer.render(this.scene,this.camera);}
}
